services:
    _defaults:
        autowire: true
        autoconfigure: true

    Fk\Example\:
        resource: '../../'

    Fk\Example\Controller\CustomController:
        calls:
            - setContainer: ['@service_container']
            - setTwig: ['@twig']